# Generated by Django 5.1.7 on 2025-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keylogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystroke',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
