# Generated by Django 5.1.7 on 2025-03-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keylogger', '0002_alter_keystroke_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystroke',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='keystroke',
            name='dd_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keystroke',
            name='flight_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keystroke',
            name='hold_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keystroke',
            name='press_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keystroke',
            name='release_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keystroke',
            name='ud_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
