# Generated by Django 5.1.7 on 2025-03-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keylogger', '0003_remove_keystroke_timestamp_keystroke_dd_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystroke',
            name='dd_time',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='flight_time',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='hold_time',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='press_time',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='release_time',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='ud_time',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
