# Generated by Django 5.1.7 on 2025-03-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keylogger', '0005_alter_keystroke_dd_time_alter_keystroke_flight_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystroke',
            name='ud_time',
        ),
    ]
