# Generated by Django 5.1.7 on 2025-03-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keylogger', '0006_remove_keystroke_ud_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystroke',
            name='dd_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='flight_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='hold_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='press_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='release_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='keystroke',
            name='user_ip',
            field=models.CharField(max_length=45),
        ),
    ]
