# Generated by Django 5.1.7 on 2025-04-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keylogger', '0008_alter_keystroke_dd_time_alter_keystroke_flight_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystroke',
            name='press_time',
        ),
        migrations.RemoveField(
            model_name='keystroke',
            name='release_time',
        ),
        migrations.RemoveField(
            model_name='keystroke',
            name='user_ip',
        ),
    ]
